all:
  hosts:
    node-0:
      ansible_host: 158.160.111.242
      ansible_user: ubuntu
    node-1:
      ansible_host: 158.160.73.73
      ansible_user: ubuntu
    node-2:
      ansible_host: 158.160.145.55
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        node-0:        
    kube_node:
      hosts:        
        node-1:
        node-2:
    etcd:
      hosts:
        node-0:        
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
